/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ele.me.hackathon.tank.player;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-11-13")
public class Order implements org.apache.thrift.TBase<Order, Order._Fields>, java.io.Serializable, Cloneable, Comparable<Order> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Order");

  private static final org.apache.thrift.protocol.TField TANK_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("tankId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField ORDER_FIELD_DESC = new org.apache.thrift.protocol.TField("order", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField DIR_FIELD_DESC = new org.apache.thrift.protocol.TField("dir", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new OrderStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new OrderTupleSchemeFactory();

  /**
   * DO NOT try to send a order with competitor's tank id.
   * In that case, game engine will treat it as cheat and would ignore ALL this player's orders in this round.
   * 
   */
  public int tankId; // required
  /**
   * Possible orders are: turnTo, fire, move. All others words are illegal and will be ignored.
   * If want a tank to stick around, just do NOT send any order with that tank.
   * 
   */
  public java.lang.String order; // required
  /**
   * the dir are always on base of the map instead of the tank itself,
   * which mean if a 'fire' order with UP direction will made the tank fire a shell toward the UP diction of the map.
   * 
   * Only move order does not need a direction, in that case just give a direction and game engine will ignore it.
   * 
   * 
   * @see Direction
   */
  public Direction dir; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * DO NOT try to send a order with competitor's tank id.
     * In that case, game engine will treat it as cheat and would ignore ALL this player's orders in this round.
     * 
     */
    TANK_ID((short)1, "tankId"),
    /**
     * Possible orders are: turnTo, fire, move. All others words are illegal and will be ignored.
     * If want a tank to stick around, just do NOT send any order with that tank.
     * 
     */
    ORDER((short)2, "order"),
    /**
     * the dir are always on base of the map instead of the tank itself,
     * which mean if a 'fire' order with UP direction will made the tank fire a shell toward the UP diction of the map.
     * 
     * Only move order does not need a direction, in that case just give a direction and game engine will ignore it.
     * 
     * 
     * @see Direction
     */
    DIR((short)3, "dir");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TANK_ID
          return TANK_ID;
        case 2: // ORDER
          return ORDER;
        case 3: // DIR
          return DIR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TANKID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TANK_ID, new org.apache.thrift.meta_data.FieldMetaData("tankId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ORDER, new org.apache.thrift.meta_data.FieldMetaData("order", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DIR, new org.apache.thrift.meta_data.FieldMetaData("dir", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, Direction.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Order.class, metaDataMap);
  }

  public Order() {
  }

  public Order(
    int tankId,
    java.lang.String order,
    Direction dir)
  {
    this();
    this.tankId = tankId;
    setTankIdIsSet(true);
    this.order = order;
    this.dir = dir;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Order(Order other) {
    __isset_bitfield = other.__isset_bitfield;
    this.tankId = other.tankId;
    if (other.isSetOrder()) {
      this.order = other.order;
    }
    if (other.isSetDir()) {
      this.dir = other.dir;
    }
  }

  public Order deepCopy() {
    return new Order(this);
  }

  @Override
  public void clear() {
    setTankIdIsSet(false);
    this.tankId = 0;
    this.order = null;
    this.dir = null;
  }

  /**
   * DO NOT try to send a order with competitor's tank id.
   * In that case, game engine will treat it as cheat and would ignore ALL this player's orders in this round.
   * 
   */
  public int getTankId() {
    return this.tankId;
  }

  /**
   * DO NOT try to send a order with competitor's tank id.
   * In that case, game engine will treat it as cheat and would ignore ALL this player's orders in this round.
   * 
   */
  public Order setTankId(int tankId) {
    this.tankId = tankId;
    setTankIdIsSet(true);
    return this;
  }

  public void unsetTankId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TANKID_ISSET_ID);
  }

  /** Returns true if field tankId is set (has been assigned a value) and false otherwise */
  public boolean isSetTankId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TANKID_ISSET_ID);
  }

  public void setTankIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TANKID_ISSET_ID, value);
  }

  /**
   * Possible orders are: turnTo, fire, move. All others words are illegal and will be ignored.
   * If want a tank to stick around, just do NOT send any order with that tank.
   * 
   */
  public java.lang.String getOrder() {
    return this.order;
  }

  /**
   * Possible orders are: turnTo, fire, move. All others words are illegal and will be ignored.
   * If want a tank to stick around, just do NOT send any order with that tank.
   * 
   */
  public Order setOrder(java.lang.String order) {
    this.order = order;
    return this;
  }

  public void unsetOrder() {
    this.order = null;
  }

  /** Returns true if field order is set (has been assigned a value) and false otherwise */
  public boolean isSetOrder() {
    return this.order != null;
  }

  public void setOrderIsSet(boolean value) {
    if (!value) {
      this.order = null;
    }
  }

  /**
   * the dir are always on base of the map instead of the tank itself,
   * which mean if a 'fire' order with UP direction will made the tank fire a shell toward the UP diction of the map.
   * 
   * Only move order does not need a direction, in that case just give a direction and game engine will ignore it.
   * 
   * 
   * @see Direction
   */
  public Direction getDir() {
    return this.dir;
  }

  /**
   * the dir are always on base of the map instead of the tank itself,
   * which mean if a 'fire' order with UP direction will made the tank fire a shell toward the UP diction of the map.
   * 
   * Only move order does not need a direction, in that case just give a direction and game engine will ignore it.
   * 
   * 
   * @see Direction
   */
  public Order setDir(Direction dir) {
    this.dir = dir;
    return this;
  }

  public void unsetDir() {
    this.dir = null;
  }

  /** Returns true if field dir is set (has been assigned a value) and false otherwise */
  public boolean isSetDir() {
    return this.dir != null;
  }

  public void setDirIsSet(boolean value) {
    if (!value) {
      this.dir = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case TANK_ID:
      if (value == null) {
        unsetTankId();
      } else {
        setTankId((java.lang.Integer)value);
      }
      break;

    case ORDER:
      if (value == null) {
        unsetOrder();
      } else {
        setOrder((java.lang.String)value);
      }
      break;

    case DIR:
      if (value == null) {
        unsetDir();
      } else {
        setDir((Direction)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TANK_ID:
      return getTankId();

    case ORDER:
      return getOrder();

    case DIR:
      return getDir();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TANK_ID:
      return isSetTankId();
    case ORDER:
      return isSetOrder();
    case DIR:
      return isSetDir();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Order)
      return this.equals((Order)that);
    return false;
  }

  public boolean equals(Order that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_tankId = true;
    boolean that_present_tankId = true;
    if (this_present_tankId || that_present_tankId) {
      if (!(this_present_tankId && that_present_tankId))
        return false;
      if (this.tankId != that.tankId)
        return false;
    }

    boolean this_present_order = true && this.isSetOrder();
    boolean that_present_order = true && that.isSetOrder();
    if (this_present_order || that_present_order) {
      if (!(this_present_order && that_present_order))
        return false;
      if (!this.order.equals(that.order))
        return false;
    }

    boolean this_present_dir = true && this.isSetDir();
    boolean that_present_dir = true && that.isSetDir();
    if (this_present_dir || that_present_dir) {
      if (!(this_present_dir && that_present_dir))
        return false;
      if (!this.dir.equals(that.dir))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + tankId;

    hashCode = hashCode * 8191 + ((isSetOrder()) ? 131071 : 524287);
    if (isSetOrder())
      hashCode = hashCode * 8191 + order.hashCode();

    hashCode = hashCode * 8191 + ((isSetDir()) ? 131071 : 524287);
    if (isSetDir())
      hashCode = hashCode * 8191 + dir.getValue();

    return hashCode;
  }

  @Override
  public int compareTo(Order other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetTankId()).compareTo(other.isSetTankId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTankId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tankId, other.tankId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetOrder()).compareTo(other.isSetOrder());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOrder()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.order, other.order);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDir()).compareTo(other.isSetDir());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDir()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dir, other.dir);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Order(");
    boolean first = true;

    sb.append("tankId:");
    sb.append(this.tankId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("order:");
    if (this.order == null) {
      sb.append("null");
    } else {
      sb.append(this.order);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("dir:");
    if (this.dir == null) {
      sb.append("null");
    } else {
      sb.append(this.dir);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class OrderStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public OrderStandardScheme getScheme() {
      return new OrderStandardScheme();
    }
  }

  private static class OrderStandardScheme extends org.apache.thrift.scheme.StandardScheme<Order> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Order struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TANK_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.tankId = iprot.readI32();
              struct.setTankIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ORDER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.order = iprot.readString();
              struct.setOrderIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DIR
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.dir = ele.me.hackathon.tank.player.Direction.findByValue(iprot.readI32());
              struct.setDirIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Order struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(TANK_ID_FIELD_DESC);
      oprot.writeI32(struct.tankId);
      oprot.writeFieldEnd();
      if (struct.order != null) {
        oprot.writeFieldBegin(ORDER_FIELD_DESC);
        oprot.writeString(struct.order);
        oprot.writeFieldEnd();
      }
      if (struct.dir != null) {
        oprot.writeFieldBegin(DIR_FIELD_DESC);
        oprot.writeI32(struct.dir.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class OrderTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public OrderTupleScheme getScheme() {
      return new OrderTupleScheme();
    }
  }

  private static class OrderTupleScheme extends org.apache.thrift.scheme.TupleScheme<Order> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Order struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetTankId()) {
        optionals.set(0);
      }
      if (struct.isSetOrder()) {
        optionals.set(1);
      }
      if (struct.isSetDir()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetTankId()) {
        oprot.writeI32(struct.tankId);
      }
      if (struct.isSetOrder()) {
        oprot.writeString(struct.order);
      }
      if (struct.isSetDir()) {
        oprot.writeI32(struct.dir.getValue());
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Order struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.tankId = iprot.readI32();
        struct.setTankIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.order = iprot.readString();
        struct.setOrderIsSet(true);
      }
      if (incoming.get(2)) {
        struct.dir = ele.me.hackathon.tank.player.Direction.findByValue(iprot.readI32());
        struct.setDirIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

